In [12]:
import pandas as pd
import numpy as np
df = pd.read_csv('parc_voitures_par_type_energie.csv')
df

,id,Type energie,Type voiture,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,1,Gazole,particulier,0,21654866,22255893,22807569,23297792,23595636,23738794,23681770,23178814,22621240,21941256
1,2,Gazole hybride non rechargeable,particulier,0,584,9124,22538,32413,50886,54713,54776,55706,64692,87269
2,3,Gazole hybride rechargeable,particulier,0,104,266,520,559,591,770,1027,1225,1873,4054
3,4,Essence,particulier,0,13345276,13006654,12856477,12858899,13035734,13351438,13815763,14367508,14993713,15201479
4,5,Essence hybride non rechargeable,particulier,0,11003,25117,57666,89227,123970,167821,234000,320798,411888,556651
5,6,Essence hybride rechargeable,particulier,0,27918,30434,29937,31064,35731,42158,53208,66661,82822,153392
6,7,Electrique et hydrogène,particulier,0,4292,9493,17144,25883,41735,61106,82306,106332,140871,244863
7,8,Gaz,particulier,0,204735,190682,184752,176462,172259,165686,159528,152650,146111,153769
8,9,Inconnu,particulier,0,3853,4065,4001,4073,4156,4238,4208,4157,3980,3533
9,10,Gazole,entreprise,0,1754721,1789120,1826577,1855413,1907412,1965945,2028804,2015293,1920454,1788881
10,11,Gazole hybride non rechargeable,entreprise,0,582,4950,10919,14633,23311,20369,16597,13538,15726,24008
11,12,Gazole hybride rechargeable,entreprise,0,99,118,264,272,280,422,568,695,1243,2769
12,13,Essence,entreprise,0,441193,411225,410417,431832,472284,552898,633317,755670,934082,879868
13,14,Essence hybride non rechargeable,entreprise,0,1931,5640,13434,20939,28653,38303,47259,61639,83349,119617
14,15,Essence hybride rechargeable,entreprise,0,7286,6355,5229,4944,6562,10201,16296,23402,32529,74549
15,16,Electrique et hydrogène,entreprise,0,3487,6325,10121,14564,18862,24823,31830,42195,53365,90409
16,17,Gaz,entreprise,0,12949,11972,10983,10209,9397,8888,8273,7705,7196,8751
17,18,Inconnu,entreprise,0,122,114,132,146,162,188,206,208,197,166
18,19,Gazole,transport commun,0,0,0,87603,88088,87779,88412,88970,88592,88421,86142
19,20,Gazole hybride non rechargeable,transport commun,0,0,0,209,263,581,1194,1418,1683,1857,2188
20,21,Gazole hybride rechargeable,transport commun,0,0,0,120,75,69,69,69,74,72,73
21,22,Essence,transport commun,0,0,0,31,23,13,6,1,1,15,15
22,23,Essence hybride non rechargeable,transport commun,0,0,0,0,0,0,0,0,0,1,2
23,24,Electrique et hydrogène,transport commun,0,0,0,271,292,314,368,443,525,789,938
24,25,Gaz,transport commun,0,0,0,2642,2604,2648,2715,2819,2946,3285,4080
25,26,Inconnu,transport commun,0,0,0,94,95,88,84,81,74,66,67

In [13]:
df.dtypes

id               int64
Type energie    object
Type voiture    object
2011             int64
2012             int64
2013             int64
2014             int64
2015             int64
2016             int64
2017             int64
2018             int64
2019             int64
2020             int64
2021             int64
dtype: object

In [17]:
df = df.rename(columns={'Type energie':'type_energie','Type voiture':'type_voiture'})

In [18]:
df.shape

(26, 14)

In [19]:
melted_df = pd.melt(df, id_vars=['id', 'type_energie', 'type_voiture'], 
                       var_name='annee', value_name='valeur')
melted_df

     id                      type_energie      type_voiture annee  valeur
0     1                            Gazole       particulier  2011       0
1     2   Gazole hybride non rechargeable       particulier  2011       0
2     3       Gazole hybride rechargeable       particulier  2011       0
3     4                           Essence       particulier  2011       0
4     5  Essence hybride non rechargeable       particulier  2011       0
..   ..                               ...               ...   ...     ...
281  22                           Essence  transport commun  2021      15
282  23  Essence hybride non rechargeable  transport commun  2021       2
283  24           Electrique et hydrogène  transport commun  2021     938
284  25                               Gaz  transport commun  2021    4080
285  26                           Inconnu  transport commun  2021      67

[286 rows x 5 columns]

In [21]:
melted_df['id'] = range(1, len(melted_df) + 1)
melted_df

      id                      type_energie      type_voiture annee  valeur
0      1                            Gazole       particulier  2011       0
1      2   Gazole hybride non rechargeable       particulier  2011       0
2      3       Gazole hybride rechargeable       particulier  2011       0
3      4                           Essence       particulier  2011       0
4      5  Essence hybride non rechargeable       particulier  2011       0
..   ...                               ...               ...   ...     ...
281  282                           Essence  transport commun  2021      15
282  283  Essence hybride non rechargeable  transport commun  2021       2
283  284           Electrique et hydrogène  transport commun  2021     938
284  285                               Gaz  transport commun  2021    4080
285  286                           Inconnu  transport commun  2021      67

[286 rows x 5 columns]

In [5]:
#for column in df.select_dtypes(include=['float64']).columns:
#df[column] = df[column].fillna(0).astype(int)

In [26]:
from unidecode import unidecode
melted_df['type_energie'] = melted_df['type_energie'].apply(unidecode)
melted_df['type_voiture'] = melted_df['type_voiture'].apply(unidecode)

In [28]:
melted_df.to_csv('parc_voitures_par_type_energie_ev', index=False)